application-description: '@project.description@'
application-version: '@project.version@'
logging:
    level:
        org:
            springframework:
                boot:
                    autoconfigure: ERROR
#server:
   # forward-headers-strategy: NATIVE
   # tomcat:
    #    remote-ip-header: x-forwarded-for
application:
    clients:
        - username: rw
          password: secret123
          roles: READ,WRITE
        - username: r
          password: secret123
          roles: READ
        - username: w
          password: secret123
          roles: WRITE